# Copyright (c) 2026 Sascha G. Eurich, Melowsyne UNIPESSOAL LDA
# SPDX-License-Identifier: MIT

# GENERATED by fountain_proto_schema/generate.py — DO NOT EDIT.
# Source: fountain_proto_schema/schema.py

from __future__ import annotations
from dataclasses import dataclass
from enum import IntEnum
from typing import Any, Optional


class MsgType(IntEnum):
    HELLO = 0
    HELLO_ACK = 1
    PROTOCOL_MISMATCH = 2
    OTA_CHECK = 3
    OTA_AVAILABLE = 4
    OTA_NONE = 5
    OTA_CANCEL = 6
    OTA_STATUS = 7
    HEARTBEAT = 8
    DP_REPORT = 9
    DP_READ = 10
    DP_WRITE = 11
    DP_WRITE_RESULT = 12
    COMMAND = 13
    COMMAND_RESULT = 14
    ERROR_REPORT = 15
    DEVICE_ALERT = 16
    # Logging pull (Logging_v1.md, work package 3). NOTE: added by hand —
    # fold into fountain_proto_schema/schema.py when the generator is used
    # again (the generator tree is not part of this repo).
    LOG_READ = 17
    LOG_BATCH = 18
    LOG_READ_PREV = 19
    LOG_ACK_PREV = 20
    LOG_ACK_RESULT = 21
    # Pressure history (drucksensor_datenstruktur.md): read back the device's
    # 1 Hz sample ring (chart backfill). Also added by hand; values must
    # match fountain_msgs.h (FP_MSG_HISTORY_*).
    HISTORY_READ = 22
    HISTORY_BATCH = 23


WIRE_VERSION = 2
HANDSHAKE_VERSION = 1
AUTH_SCHEME = "hmac-sha256"
AUTH_SCOPE = "control"
SESSION_PROOF_MSG = "ota_check"

# name -> metadata
META: dict[str, dict[str, Any]] = {
    "hello": {"direction": "c2s", "wire": 1, "auth": "none", "request": True, "response": "hello_ack"},
    "hello_ack": {"direction": "s2c", "wire": 1, "auth": "none", "request": False, "response": None},
    "protocol_mismatch": {"direction": "c2s", "wire": 1, "auth": "none", "request": False, "response": None},
    "ota_check": {"direction": "c2s", "wire": 2, "auth": "session", "request": True, "response": "ota_available"},
    "ota_available": {"direction": "s2c", "wire": 2, "auth": "control", "request": False, "response": "ota_status"},
    "ota_none": {"direction": "s2c", "wire": 2, "auth": "none", "request": False, "response": None},
    "ota_cancel": {"direction": "s2c", "wire": 2, "auth": "control", "request": False, "response": "ota_status"},
    "ota_status": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "heartbeat": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "dp_report": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "dp_read": {"direction": "s2c", "wire": 2, "auth": "none", "request": True, "response": "dp_report"},
    "dp_write": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "dp_write_result"},
    "dp_write_result": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "command": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "command_result"},
    "command_result": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "error_report": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "device_alert": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "log_read": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "log_batch"},
    "log_batch": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "log_read_prev": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "log_batch"},
    "log_ack_prev": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "log_ack_result"},
    "log_ack_result": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
    "history_read": {"direction": "s2c", "wire": 2, "auth": "control", "request": True, "response": "history_batch"},
    "history_batch": {"direction": "c2s", "wire": 2, "auth": "none", "request": False, "response": None},
}


@dataclass
class Hello:
    """hello (c2s, auth=none) — First message after each WS handshake; identity + negotiation."""
    NAME = "hello"
    device_id: Optional[str] = None
    protocol_version: Optional[int] = None
    fw_version: Optional[str] = None
    hw_rev: Optional[str] = None
    boot_reason: Optional[str] = None
    auth_schemes: Optional[list] = None
    auth_kids: Optional[list] = None
    client_nonce: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.device_id is not None: b["device_id"] = self.device_id
        if self.protocol_version is not None: b["protocol_version"] = self.protocol_version
        if self.fw_version is not None: b["fw_version"] = self.fw_version
        if self.hw_rev is not None: b["hw_rev"] = self.hw_rev
        if self.boot_reason is not None: b["boot_reason"] = self.boot_reason
        if self.auth_schemes is not None: b["auth_schemes"] = self.auth_schemes
        if self.auth_kids is not None: b["auth_kids"] = self.auth_kids
        if self.client_nonce is not None: b["client_nonce"] = self.client_nonce
        return b

    @classmethod
    def from_body(cls, d: dict) -> "Hello":
        for k in ['device_id', 'protocol_version', 'fw_version']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(device_id=d.get("device_id"), protocol_version=d.get("protocol_version"), fw_version=d.get("fw_version"), hw_rev=d.get("hw_rev"), boot_reason=d.get("boot_reason"), auth_schemes=d.get("auth_schemes"), auth_kids=d.get("auth_kids"), client_nonce=d.get("client_nonce"))


@dataclass
class HelloAck:
    """hello_ack (s2c, auth=none) — Response to hello: acceptance, protocol/auth negotiation."""
    NAME = "hello_ack"
    accepted: Optional[bool] = None
    supported_protocols: Optional[list] = None
    server_ts: Optional[int] = None
    reason: Optional[str] = None
    auth_required: Optional[bool] = None
    auth_scheme: Optional[str] = None
    auth_scope: Optional[str] = None
    auth_kid: Optional[str] = None
    server_nonce: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.accepted is not None: b["accepted"] = self.accepted
        if self.supported_protocols is not None: b["supported_protocols"] = self.supported_protocols
        if self.server_ts is not None: b["server_ts"] = self.server_ts
        if self.reason is not None: b["reason"] = self.reason
        if self.auth_required is not None: b["auth_required"] = self.auth_required
        if self.auth_scheme is not None: b["auth_scheme"] = self.auth_scheme
        if self.auth_scope is not None: b["auth_scope"] = self.auth_scope
        if self.auth_kid is not None: b["auth_kid"] = self.auth_kid
        if self.server_nonce is not None: b["server_nonce"] = self.server_nonce
        return b

    @classmethod
    def from_body(cls, d: dict) -> "HelloAck":
        for k in ['accepted', 'supported_protocols', 'server_ts']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(accepted=d.get("accepted"), supported_protocols=d.get("supported_protocols"), server_ts=d.get("server_ts"), reason=d.get("reason"), auth_required=d.get("auth_required"), auth_scheme=d.get("auth_scheme"), auth_scope=d.get("auth_scope"), auth_kid=d.get("auth_kid"), server_nonce=d.get("server_nonce"))


@dataclass
class ProtocolMismatch:
    """protocol_mismatch (c2s, auth=none) — No common protocol version; the device disconnects afterwards."""
    NAME = "protocol_mismatch"
    device_protocols: Optional[list] = None
    server_protocols: Optional[list] = None
    reason: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.device_protocols is not None: b["device_protocols"] = self.device_protocols
        if self.server_protocols is not None: b["server_protocols"] = self.server_protocols
        if self.reason is not None: b["reason"] = self.reason
        return b

    @classmethod
    def from_body(cls, d: dict) -> "ProtocolMismatch":
        for k in ['device_protocols', 'server_protocols', 'reason']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(device_protocols=d.get("device_protocols"), server_protocols=d.get("server_protocols"), reason=d.get("reason"))


@dataclass
class OtaCheck:
    """ota_check (c2s, auth=session) — One-time update query after boot; carries the session proof."""
    NAME = "ota_check"
    current_version: Optional[str] = None
    hw_rev: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.current_version is not None: b["current_version"] = self.current_version
        if self.hw_rev is not None: b["hw_rev"] = self.hw_rev
        return b

    @classmethod
    def from_body(cls, d: dict) -> "OtaCheck":
        for k in ['current_version']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(current_version=d.get("current_version"), hw_rev=d.get("hw_rev"))


@dataclass
class OtaAvailable:
    """ota_available (s2c, auth=control) — Update available: URL + verification data (server-attested via MAC)."""
    NAME = "ota_available"
    target_version: Optional[str] = None
    url: Optional[str] = None
    size: Optional[int] = None
    crc32: Optional[int] = None
    sha256: Optional[str] = None
    mandatory: Optional[bool] = None
    max_attempts: Optional[int] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.target_version is not None: b["target_version"] = self.target_version
        if self.url is not None: b["url"] = self.url
        if self.size is not None: b["size"] = self.size
        if self.crc32 is not None: b["crc32"] = self.crc32
        if self.sha256 is not None: b["sha256"] = self.sha256
        if self.mandatory is not None: b["mandatory"] = self.mandatory
        if self.max_attempts is not None: b["max_attempts"] = self.max_attempts
        return b

    @classmethod
    def from_body(cls, d: dict) -> "OtaAvailable":
        for k in ['target_version', 'url', 'size', 'crc32', 'sha256', 'mandatory']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(target_version=d.get("target_version"), url=d.get("url"), size=d.get("size"), crc32=d.get("crc32"), sha256=d.get("sha256"), mandatory=d.get("mandatory"), max_attempts=d.get("max_attempts"))


@dataclass
class OtaNone:
    """ota_none (s2c, auth=none) — Response to ota_check: no update."""
    NAME = "ota_none"
    pass

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        return b

    @classmethod
    def from_body(cls, d: dict) -> "OtaNone":
        return cls()


@dataclass
class OtaCancel:
    """ota_cancel (s2c, auth=control) — Abort the running OTA."""
    NAME = "ota_cancel"
    reason: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.reason is not None: b["reason"] = self.reason
        return b

    @classmethod
    def from_body(cls, d: dict) -> "OtaCancel":
        return cls(reason=d.get("reason"))


@dataclass
class OtaStatus:
    """ota_status (c2s, auth=none) — OTA progress/result."""
    NAME = "ota_status"
    target_version: Optional[str] = None
    state: Optional[str] = None
    attempt: Optional[int] = None
    progress_pct: Optional[int] = None
    error: Optional[str] = None
    error_detail: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.target_version is not None: b["target_version"] = self.target_version
        if self.state is not None: b["state"] = self.state
        if self.attempt is not None: b["attempt"] = self.attempt
        if self.progress_pct is not None: b["progress_pct"] = self.progress_pct
        if self.error is not None: b["error"] = self.error
        if self.error_detail is not None: b["error_detail"] = self.error_detail
        return b

    @classmethod
    def from_body(cls, d: dict) -> "OtaStatus":
        for k in ['target_version', 'state']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(target_version=d.get("target_version"), state=d.get("state"), attempt=d.get("attempt"), progress_pct=d.get("progress_pct"), error=d.get("error"), error_detail=d.get("error_detail"))


@dataclass
class Heartbeat:
    """heartbeat (c2s, auth=none) — Lightweight liveness/health message."""
    NAME = "heartbeat"
    uptime_s: Optional[int] = None
    fw_version: Optional[str] = None
    fault_active: Optional[bool] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.uptime_s is not None: b["uptime_s"] = self.uptime_s
        if self.fw_version is not None: b["fw_version"] = self.fw_version
        if self.fault_active is not None: b["fault_active"] = self.fault_active
        return b

    @classmethod
    def from_body(cls, d: dict) -> "Heartbeat":
        for k in ['uptime_s', 'fw_version']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(uptime_s=d.get("uptime_s"), fw_version=d.get("fw_version"), fault_active=d.get("fault_active"))


@dataclass
class DpReport:
    """dp_report (c2s, auth=none) — Datapoint values (cyclic / on-change / response to dp_read)."""
    NAME = "dp_report"
    seq: Optional[int] = None
    dp: Optional[dict] = None
    unknown: Optional[list] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.seq is not None: b["seq"] = self.seq
        if self.dp is not None: b["dp"] = self.dp
        if self.unknown is not None: b["unknown"] = self.unknown
        return b

    @classmethod
    def from_body(cls, d: dict) -> "DpReport":
        for k in ['seq', 'dp']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(seq=d.get("seq"), dp=d.get("dp"), unknown=d.get("unknown"))


@dataclass
class DpRead:
    """dp_read (s2c, auth=none) — Query datapoint values ([] = full snapshot)."""
    NAME = "dp_read"
    names: Optional[list] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.names is not None: b["names"] = self.names
        return b

    @classmethod
    def from_body(cls, d: dict) -> "DpRead":
        for k in ['names']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(names=d.get("names"))


@dataclass
class DpWrite:
    """dp_write (s2c, auth=control) — Set writable datapoints (atomic)."""
    NAME = "dp_write"
    dp: Optional[dict] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.dp is not None: b["dp"] = self.dp
        return b

    @classmethod
    def from_body(cls, d: dict) -> "DpWrite":
        for k in ['dp']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(dp=d.get("dp"))


@dataclass
class DpWriteResult:
    """dp_write_result (c2s, auth=none) — Result of the atomic dp_write."""
    NAME = "dp_write_result"
    status: Optional[str] = None
    errors: Optional[dict] = None
    readback: Optional[dict] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.status is not None: b["status"] = self.status
        if self.errors is not None: b["errors"] = self.errors
        if self.readback is not None: b["readback"] = self.readback
        return b

    @classmethod
    def from_body(cls, d: dict) -> "DpWriteResult":
        for k in ['status']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(status=d.get("status"), errors=d.get("errors"), readback=d.get("readback"))


@dataclass
class Command:
    """command (s2c, auth=control) — Control action (set_state, restart, turn_on_duration, ...)."""
    NAME = "command"
    command: Optional[str] = None
    target_state: Optional[str] = None
    duration_steps: Optional[int] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.command is not None: b["command"] = self.command
        if self.target_state is not None: b["target_state"] = self.target_state
        if self.duration_steps is not None: b["duration_steps"] = self.duration_steps
        return b

    @classmethod
    def from_body(cls, d: dict) -> "Command":
        for k in ['command']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(command=d.get("command"), target_state=d.get("target_state"), duration_steps=d.get("duration_steps"))


@dataclass
class CommandResult:
    """command_result (c2s, auth=none) — Confirmation after the target state is reached."""
    NAME = "command_result"
    command: Optional[str] = None
    status: Optional[str] = None
    error: Optional[str] = None
    error_detail: Optional[str] = None
    retry_after_s: Optional[int] = None
    readback: Optional[dict] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.command is not None: b["command"] = self.command
        if self.status is not None: b["status"] = self.status
        if self.error is not None: b["error"] = self.error
        if self.error_detail is not None: b["error_detail"] = self.error_detail
        if self.retry_after_s is not None: b["retry_after_s"] = self.retry_after_s
        if self.readback is not None: b["readback"] = self.readback
        return b

    @classmethod
    def from_body(cls, d: dict) -> "CommandResult":
        for k in ['command', 'status']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(command=d.get("command"), status=d.get("status"), error=d.get("error"), error_detail=d.get("error_detail"), retry_after_s=d.get("retry_after_s"), readback=d.get("readback"))


@dataclass
class ErrorReport:
    """error_report (c2s, auth=none) — Full error status (response to get_error_report)."""
    NAME = "error_report"
    status: Optional[str] = None
    active_faults: Optional[list] = None
    log: Optional[list] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.status is not None: b["status"] = self.status
        if self.active_faults is not None: b["active_faults"] = self.active_faults
        if self.log is not None: b["log"] = self.log
        return b

    @classmethod
    def from_body(cls, d: dict) -> "ErrorReport":
        for k in ['status']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(status=d.get("status"), active_faults=d.get("active_faults"), log=d.get("log"))


@dataclass
class DeviceAlert:
    """device_alert (c2s, auth=none) — Unsolicited alert on a new fault/critical."""
    NAME = "device_alert"
    code: Optional[str] = None
    severity: Optional[str] = None
    datapoint: Optional[str] = None
    value: Optional[float] = None
    threshold: Optional[float] = None
    detail: Optional[str] = None

    def to_body(self) -> dict:
        b: dict[str, Any] = {}
        if self.code is not None: b["code"] = self.code
        if self.severity is not None: b["severity"] = self.severity
        if self.datapoint is not None: b["datapoint"] = self.datapoint
        if self.value is not None: b["value"] = self.value
        if self.threshold is not None: b["threshold"] = self.threshold
        if self.detail is not None: b["detail"] = self.detail
        return b

    @classmethod
    def from_body(cls, d: dict) -> "DeviceAlert":
        for k in ['code', 'severity']:
            if k not in d:
                raise ValueError(f"%s: required field {k} missing" % cls.NAME)
        return cls(code=d.get("code"), severity=d.get("severity"), datapoint=d.get("datapoint"), value=d.get("value"), threshold=d.get("threshold"), detail=d.get("detail"))


MESSAGE_CLASSES = {
    "hello": Hello,
    "hello_ack": HelloAck,
    "protocol_mismatch": ProtocolMismatch,
    "ota_check": OtaCheck,
    "ota_available": OtaAvailable,
    "ota_none": OtaNone,
    "ota_cancel": OtaCancel,
    "ota_status": OtaStatus,
    "heartbeat": Heartbeat,
    "dp_report": DpReport,
    "dp_read": DpRead,
    "dp_write": DpWrite,
    "dp_write_result": DpWriteResult,
    "command": Command,
    "command_result": CommandResult,
    "error_report": ErrorReport,
    "device_alert": DeviceAlert,
}
